### ISSUE TITLE
CLOSE button not being clicked

### ISSUE THREAD

**Issue by ctrlsam** [xulusjb/PUBG#13]
The CLOSE button in REGION menu is not being clicked as the cursor is slightly off. I am running 1920*1080  in fullscreen windowed.

**Comment by lunettekyura** [comment]
what mouse are you using right now ? report rate maybe the issue, set to 500hz or 250hz

**Comment by ctrlsam** [comment]
In using the Razer mamba

**Comment by lunettekyura** [comment]
@SillySam okay sam, i don't know much of razer mouse honestly but maybe you can change the report rate or people more similar with 'polling rate' mouse you are using right now, set to 500hz or lower maybe will do the trick, and maybe razer synapse has a setting for polling rate, in my personal opinion the polling rate has many issues with macro program that we are using for pubg, i have to change my polling/report rate to 500 before get this thing to work, so yeah maybeeeee polling rate is the issues right here

**Comment by ctrlsam** [comment]
Thanks I'll check it out
:)

**Comment by hiroto-takatoshi** [comment]
Yes, after the lock of kr/jp servers the button positions changed. We will compile a new version and make release.

**Comment by hiroto-takatoshi** [comment]
Also folks, i would like to know whether your server list is the same as in this screenshot.
![title](https://user-images.githubusercontent.com/11675824/37988004-be43c5dc-323a-11e8-9475-f6877c500d46.png)

**Comment by ctrlsam** [comment]
Yes, the menu is exactly like the screenshot.

**Comment by lunettekyura** [comment]
Yes. the menu look the same as mine, @hiroto-takatoshi please make 'after compiled' one, like 0313

**Comment by xulusjb** [comment]
The issue is due to the 3.27 game update. We will update the bot soon.

**Comment by hiroto-takatoshi** [comment]
https://github.com/xulusjb/PUBG/releases/tag/1.4 @SillySam @lunettekyura
