### ISSUE TITLE
0410版本开启了没有动静

### ISSUE THREAD

**Issue by caobidawang** [xulusjb/PUBG#19]
都按照设置的弄好了，只能会自动运行游戏，不会进入战局啊。
是我的原因吗？

**Comment by hiroto-takatoshi** [comment]
[0411.zip](https://github.com/xulusjb/PUBG/files/1896580/0411.zip)
试一下这个版本行不行

**Comment by hiroto-takatoshi** [comment]
还有就是要先开游戏后开这个，不然有时会闪退

**Comment by caoliu1118** [comment]
同样的问题

**Comment by hiroto-takatoshi** [comment]
我这边都试了并没有问题，请问您是否把语言调成英文，分辨率1080全屏窗口化。如果是的话是否方便提供截图一类以便我确定具体问题。多谢。
