### ISSUE TITLE
battleye launcher

### ISSUE THREAD

**Issue by guiltyparties** [xulusjb/PUBG#6]
![screenshot_2](https://user-images.githubusercontent.com/34696970/36583990-855d4b70-18aa-11e8-8ddc-6d19dfa7a6de.png)

**Comment by xulusjb** [comment]
Are you running a source code or the exe file? Have you ever tried the counterpart?

**Comment by guiltyparties** [comment]
hi xulusjb thanks for reply, it's working now, im using source code.
how to custom resolution parameter? my screen resolution 1600x900

thankyou :)

**Comment by xulusjb** [comment]
If you want it work for a resolution other than 1920*1080， You need to read the source code and change the certain pixels the program will check or click.
